name: aura_box
description: Flutter Widget that combines multiple radial gradients and blur effect.
version: 1.0.3
homepage: https://github.com/GangemiLorenzo/aura_box

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  patrol_finders: ">=1.0.0 <3.0.0"
  very_good_analysis: ">=5.1.0 <8.0.0"
