name: Pub Publish Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_pub_publish.yml@v1
    with:
      pub_credentials: ${{secrets.PUB_CREDENTIALS}}
